In [2]:
import pandas as pd
import numpy as np

In [3]:
main_folder = r"Z:\PhD_Datasets&Analysis\Info_Inputs"
css_folder = main_folder + "\\Streamflow_Stations\Climate_Sensitive_Stations-GRDC"

filtered_css = pd.read_csv(css_folder + "//CSS_FINAL_SELECTION-MERGE_WITH_ALL.csv") # Read file with all CSS information
filtered_css

,station_name,station_no,station_id,station_latitude,station_longitude,station_status,river_name,station_elevation,CATCHMENT_SIZE,NAT_STA_ID,GRDCCOUNTRY,Continent,has_monthly_k,has_daily_k,monthly_k_recession,daily_k_recession,Next_Downstream_Station,CATCHMENT_SIZE2,Priority,Val_Analysis_Monthly_k
0,ABERCROMBIE,5204121,1075206,-33.954800,149.325200,Active,ABERCROMBIE RIVER,426.55,"2631,00 km²",412028,AU - AUSTRALIA,Oceania,Yes,No,0.420650,NaN,5204302,2631.00,432,Yes
1,ABOVE BOULEAU CREEK,4215070,1069050,50.212223,-119.538610,Active,WHITEMAN CREEK,630.00,"112,00 km²",08NM174,CA - CANADA,North America,Yes,Yes,0.350868,0.910436,4215103,112.00,773,Yes
2,"ABOVE CHENEY RESERVOIRE, KS",4125110,1069620,37.863600,-98.014800,Active,NORTH FORK NINNESCAH RIVER,443.80,"2038,30 km²",07144780,US - UNITED STATES,North America,Yes,Yes,0.417039,0.541509,4125801,2038.30,478,No
3,ABOVE FORT MCPHERSON,4208040,1068040,67.248886,-134.883060,Active,PEEL RIVER,NaN,"70600,00 km²",10MC002,CA - CANADA,North America,Yes,Yes,0.625278,0.942386,NaN,70600.00,59,No
4,"ABOVE HAMBURG, IA",4122160,1068596,40.632500,-95.625800,Active,NISHNABOTNA RIVER,272.54,"7267,50 km²",06810000,US - UNITED STATES,North America,Yes,Yes,0.549697,0.912838,4122903,7267.50,264,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,"WOODFORDS, CA (WEST FORK)",4118100,1068421,38.769600,-119.833800,Active,CARSON RIVER,1753.97,"169,38 km²",10310000,US - UNITED STATES,North America,Yes,Yes,0.593689,0.900646,NaN,169.38,732,Yes
805,XAMBIOA,3649418,1071023,-6.409700,-48.542200,Active,RIO ARAGUAIA,118.00,"364500,00 km²",28300000,BR - BRAZIL,South America,Yes,Yes,0.627802,0.974853,3649419,364500.00,20,No
806,XAVANTINA,3649617,1074892,-14.672500,-52.355000,Active,RIO DAS MORTES,266.00,"24950,00 km²",26100000,BR - BRAZIL,South America,Yes,Yes,0.786505,0.977071,3649618,24950.00,123,No
807,"YADKIN COLLEGE, NC",4148321,1069484,35.856700,-80.386900,Active,YADKIN RIVER,194.60,"5905,00 km²",02116500,US - UNITED STATES,North America,Yes,Yes,0.718625,0.896280,4148320,5905.00,294,Yes
808,ZOZA,6150400,1074154,41.724916,9.075456,Active,U RIZZANESE,354.42,"130,00 km²",Y8814010,FR - FRANCE,Europe,Yes,Yes,0.620801,0.875295,NaN,130.00,759,No

In [4]:
monthly_folder = css_folder + "\\2025-02-13_17-18_Monthly"
obs_df = pd.read_csv(monthly_folder + "//_DataFrames//Joined_Monthly_Sts_DFs_mm.csv", index_col="YYYY-MM") # Observed data in millimeters
obs_df.index = pd.to_datetime(obs_df.index, format="%Y-%m-%d").strftime("%Y-%m")  # Convert index to the right format
obs_df

,5204121,4215070,4125110,4208040,4122160,4208070,4123095,4214090,4115241,4208325,...,4116330,6606200,4148231,4125070,6605800,4118100,3649418,3649617,4148321,6150400
YYYY-MM,,,,,,,,,,,,,,,,,,,,,
1958-01,3.470416,NaN,NaN,NaN,3.204866,NaN,45.945646,NaN,55.809867,NaN,...,8.006618,NaN,72.896548,2.299292,87.894531,9.377088,NaN,NaN,55.925264,NaN
1958-02,3.269736,NaN,NaN,NaN,9.947764,NaN,40.503865,NaN,113.787247,NaN,...,9.660945,NaN,46.132995,3.327816,89.008902,11.611817,NaN,NaN,44.792277,NaN
1958-03,0.907052,NaN,NaN,NaN,11.812232,NaN,45.845750,NaN,43.858504,NaN,...,10.189360,NaN,55.845984,59.194114,71.388158,15.243698,NaN,NaN,52.594160,NaN
1958-04,1.378262,NaN,NaN,NaN,6.284285,NaN,90.753659,NaN,187.933369,NaN,...,18.598262,NaN,70.525245,15.180330,134.222085,55.778959,NaN,NaN,97.374044,NaN
1958-05,1.481213,NaN,NaN,NaN,4.226104,NaN,88.271209,NaN,135.609294,NaN,...,104.580513,NaN,78.528846,5.780134,66.537712,331.645313,NaN,NaN,69.639307,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08,NaN,NaN,NaN,NaN,3.342334,NaN,31.072611,NaN,NaN,NaN,...,11.628978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-09,NaN,NaN,NaN,NaN,1.358147,NaN,9.861389,NaN,NaN,NaN,...,9.856166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-10,NaN,NaN,NaN,NaN,1.436957,NaN,7.180309,NaN,NaN,NaN,...,9.913312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-11,NaN,NaN,NaN,NaN,1.793268,NaN,10.322834,NaN,NaN,NaN,...,11.500682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.453868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
stats_df_final = pd.read_csv(css_folder + "//runoff_monthly_stats_based-on_monthly_k.csv", index_col="Station") # Statistics DataFrame based on monthly flow series determined using monthly recession contants (k)
stats_df_final

,MAE,RMSE,Pearson_R,D1,NSE,KGE_2012,PBIAS
Station,,,,,,,
3617811,3252.751363,5230.294910,0.285006,0.380401,-6.363558,-0.267463,41.213485
3618720,1083.829084,1662.582298,0.803275,0.577933,-1.491314,0.273387,36.188209
3628400,543.290327,724.228835,0.314395,0.393099,-2.625093,-0.025888,11.354011
3630600,46.416827,82.116537,0.672288,0.579501,-1.990411,0.191085,69.693408
3635310,333.340220,483.087317,0.585637,0.543037,-1.585973,0.313288,34.069745
...,...,...,...,...,...,...,...
6854601,13.928742,20.070682,0.754435,0.591534,-0.146063,-0.129825,-24.565453
6854713,3.061158,3.974750,0.768367,0.584131,-0.059329,-0.737460,-47.713826
6855411,1.563997,2.245531,0.507312,0.465658,-1.519933,-0.671464,-30.407011
6855412,7.150258,11.716498,0.451408,0.409695,-4.861654,-0.943804,-5.695256
6870640,16.458827,22.748604,0.869963,0.659391,0.382912,-0.062671,-28.923813

In [6]:
wb_output_folder = r"Z:\PhD_Datasets&Analysis\Outputs\T&M_WBM"
bflow_df = pd.read_csv(wb_output_folder + "//bflow2//bflow2_zonal_statistics_1958-2023.csv", index_col="YYYY-MM") # Baseflow DataFrame
bflow_df

,3617110,3617811,3617812,3617814,3618051,3618052,3618500,3618700,3618711,3618720,...,6742701,6744200,6744500,6830101,6830103,6854601,6854713,6855411,6855412,6870640
YYYY-MM,,,,,,,,,,,,,,,,,,,,,
1958-01,7.484559,7.428161,7.923967,8.407091,8.145369,8.085726,7.294012,6.424676,6.594522,7.698261,...,5.730342,6.961725,7.043673,6.561404,4.649185,5.229129,5.717774,10.130124,17.335681,4.212825
1958-02,5.581120,5.546272,6.280208,7.067562,6.636699,6.539864,5.335762,4.127646,4.352435,5.935646,...,11.614347,10.672928,10.006815,15.784579,10.391970,18.179496,8.532593,20.505592,18.374847,12.880703
1958-03,4.138263,4.135383,4.978593,5.941465,5.408972,5.291005,3.914872,2.651879,2.875071,4.583528,...,15.326067,13.834860,10.940518,19.490193,13.325337,17.663210,11.546070,20.356808,20.722211,17.975669
1958-04,3.069340,3.080748,3.947721,4.994793,4.421323,4.299501,4.777978,4.221971,5.029361,5.839324,...,9.863177,11.060403,8.184048,19.892824,18.311752,23.122667,14.674276,17.894348,11.700956,25.255883
1958-05,2.279233,2.297407,3.131118,4.198957,3.605134,3.480023,9.621394,2.902642,4.810377,10.551099,...,5.612700,7.604794,5.002173,13.052485,8.513473,9.316946,8.390419,8.630968,6.602756,9.597326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08,1.089124,1.380586,1.322891,1.564264,0.008064,0.011786,2.443464,0.144626,0.462393,1.069833,...,0.578384,1.983403,0.902939,3.667914,1.049509,1.000018,2.332444,4.259922,11.576157,0.598420
2023-09,0.806723,1.025121,1.048974,1.315025,0.006359,0.009279,1.744973,0.092918,0.311779,0.803218,...,0.329133,1.364025,0.551885,2.579017,0.487936,0.407569,1.333639,2.054685,18.071234,1.420132
2023-10,0.597943,0.761868,0.831987,1.105498,0.004992,0.007271,1.247243,0.059697,0.210324,0.603993,...,0.187295,0.938099,0.337318,13.112894,15.117534,37.972613,11.399232,16.309380,13.304872,30.797106
2023-11,0.443510,0.566764,0.660063,0.929355,0.004356,0.005933,0.892320,0.038353,0.141947,0.454893,...,0.154014,4.071304,4.922911,16.543236,21.316922,42.802481,18.514031,46.762385,37.392349,24.522135
2023-12,0.641777,0.444614,0.658273,0.781278,0.055281,0.035529,0.639038,0.024641,0.095842,0.343130,...,0.796527,9.140868,8.969499,18.517979,23.743705,45.481903,23.752256,48.645471,43.706502,30.730159

In [7]:
bflow_ant_df = pd.read_csv(wb_output_folder + "//bflow2//bflow2_ant_zonal_statistics_1958-2023.csv", index_col="YYYY-MM") # Baseflow DataFrame
bflow_ant_df

,3617110,3617811,3617812,3617814,3618051,3618052,3618500,3618700,3618711,3618720,...,6742701,6744200,6744500,6830101,6830103,6854601,6854713,6855411,6855412,6870640
YYYY-MM,,,,,,,,,,,,,,,,,,,,,
1958-01,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
1958-02,7.484559,7.428161,7.923967,8.407091,8.145369,8.085726,7.294012,6.424676,6.594522,7.698261,...,5.730342,6.961725,7.043673,6.561404,4.649185,5.229129,5.717774,10.130124,17.335681,4.212825
1958-03,5.581120,5.546272,6.280208,7.067562,6.636699,6.539864,5.335762,4.127646,4.352435,5.935646,...,11.614347,10.672928,10.006815,15.784579,10.391970,18.179496,8.532593,20.505592,18.374847,12.880703
1958-04,4.138263,4.135383,4.978593,5.941465,5.408972,5.291005,3.914872,2.651879,2.875071,4.583528,...,15.326067,13.834860,10.940518,19.490193,13.325337,17.663210,11.546070,20.356808,20.722211,17.975669
1958-05,3.069340,3.080748,3.947721,4.994793,4.421323,4.299501,4.777978,4.221971,5.029361,5.839324,...,9.863177,11.060403,8.184048,19.892824,18.311752,23.122667,14.674276,17.894348,11.700956,25.255883
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08,1.471291,1.860892,1.668737,1.860742,0.010277,0.015045,3.424338,0.225110,0.686100,1.427190,...,1.016391,2.884141,1.477297,5.590136,2.257404,2.443219,4.079286,8.831977,13.009132,0.768633
2023-09,1.089124,1.380586,1.322891,1.564264,0.008064,0.011786,2.443464,0.144626,0.462393,1.069833,...,0.578384,1.983403,0.902939,3.667914,1.049509,1.000018,2.332444,4.259922,11.576157,0.598420
2023-10,0.806723,1.025121,1.048974,1.315025,0.006359,0.009279,1.744973,0.092918,0.311779,0.803218,...,0.329133,1.364025,0.551885,2.579017,0.487936,0.407569,1.333639,2.054685,18.071234,1.420132
2023-11,0.597943,0.761868,0.831987,1.105498,0.004992,0.007271,1.247243,0.059697,0.210324,0.603993,...,0.187295,0.938099,0.337318,13.112894,15.117534,37.972613,11.399232,16.309380,13.304872,30.797106
2023-12,0.443510,0.566764,0.660063,0.929355,0.004356,0.005933,0.892320,0.038353,0.141947,0.454893,...,0.154014,4.071304,4.922911,16.543236,21.316922,42.802481,18.514031,46.762385,37.392349,24.522135

In [8]:
perc_df = pd.read_csv(wb_output_folder + "//perc//perc_zonal_statistics_1958-2023.csv", index_col="YYYY-MM") # Baseflow DataFrame
perc_df

,3617110,3617811,3617812,3617814,3618051,3618052,3618500,3618700,3618711,3618720,...,6742701,6744200,6744500,6830101,6830103,6854601,6854713,6855411,6855412,6870640
YYYY-MM,,,,,,,,,,,,,,,,,,,,,
1958-01,0.324185,0.000133,8.103362e-04,2.649044e-03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.092314,0.273388,2.396081,0.000000,0.000000,2.009453,0.000000,1.025136e+01,26.836231,0.665793
1958-02,0.151839,0.087490,3.587921e-08,7.770486e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,19.384098,18.770036,14.294573,33.383906,15.381726,26.919198,12.291035,3.017273e+01,19.720687,18.193354
1958-03,0.016329,0.029190,4.185050e-08,9.887353e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,20.227344,20.730736,12.118406,26.561111,15.874064,17.314789,15.569767,2.021818e+01,23.762319,21.098437
1958-04,0.008953,0.000520,5.039776e-08,1.335688e-07,5.391800e-02,8.146261e-02,7.363466e+00,7.043347e+00,9.331825e+00,1.025632e+01,...,2.536616,4.852578,3.702972,20.661111,22.644318,26.807042,18.851163,1.560000e+01,0.015385,29.718018
1958-05,0.011520,0.000000,0.000000e+00,0.000000e+00,6.906950e-09,1.043163e-08,2.237294e+01,5.318752e-01,4.592354e+00,2.458984e+01,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08,0.000000,0.000000,0.000000e+00,0.000000e+00,5.999961e-09,9.072612e-09,4.118432e-09,9.536743e-09,5.335241e-09,7.176002e-09,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.025695,0.000000,9.710138e-07,9.720290,0.494093
2023-09,0.000000,0.000000,0.000000e+00,0.000000e+00,1.645006e-04,2.486970e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.501224,0.000000,0.007693,0.000000,3.178914e-07,26.483106,1.923769
2023-10,0.000000,0.000000,0.000000e+00,0.000000e+00,3.441665e-09,5.202051e-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,33.213255,27.828814,63.323807,24.839155,2.959091e+01,7.131884,48.802621
2023-11,0.000000,0.000000,0.000000e+00,0.000000e+00,2.460044e-03,1.279155e-03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.110067,10.967148,12.131846,23.088889,26.703409,46.061972,28.013953,7.513636e+01,68.588406,20.676126
2023-12,1.188742,0.106347,6.373529e-01,0.000000e+00,2.907834e-01,1.671693e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.627910,20.306293,15.331073,22.286111,25.852273,47.290141,30.746512,5.040000e+01,51.884058,34.535135

In [9]:
monthly_k_recessions = pd.read_csv(monthly_folder + "//Baseflow//monthly_k_recessions_df.csv", index_col="station") # Monthly recession constants (k) DataFrame
monthly_k_recessions.index.name = "Station" # Set index name to "Station"
monthly_k_recessions

         alpha_with_weights  k_recession
Station
3617110            0.306235     0.736213
3617811            0.310441     0.733124
3617812            0.236255     0.789579
3617814            0.173560     0.840667
3618051            0.191049     0.826092
...                     ...          ...
6854601            0.908978     0.402936
6854713            0.559006     0.571777
6855411            0.729128     0.482329
6855412            0.572183     0.564292
6870640            0.967575     0.380004

[808 rows x 2 columns]

In [10]:
non_containing_ws = pd.read_csv(main_folder + "\Streamflow_Sts_Drainage_Areas\GRDC_Watersheds\\non_containing_grdcno_int.csv", index_col="grdcno_int") # Watersheds not containing other GRDC watersheds
non_containing_ws

            Index
grdcno_int
3617814         0
3618700         1
3618722         2
3618950         3
3621200         4
...           ...
6854601       606
6854713       607
6855411       608
6855412       609
6870640       610

[611 rows x 1 columns]

In [11]:
def k_calculation(pbias, obs_str, perc, bflow_ant):
    """Calculates the monthly k based on PBIAS analysis."""
    pbias_fraction = -(pbias/100)
    return (np.sum(pbias_fraction * obs_str) - np.sum(perc)) / (np.sum(bflow_ant) - np.sum(perc))

In [12]:
import warnings
warnings.filterwarnings('ignore')

sts_adjusted = []
for st in monthly_k_recessions.index:
    st_str = str(st)

    # Check if station exists in all required DataFrames
    if (
        st_str in obs_df.columns
        and st_str in perc_df.columns
        and st_str in bflow_ant_df.columns
        and st in stats_df_final.index
        and st in non_containing_ws.index
    ):
        # Get the relevant columns as Series
        obs_series = obs_df[st_str]
        perc_series = perc_df[st_str]
        bflow_ant_series = bflow_ant_df[st_str]

        # Create a DataFrame to align and drop rows with any NaNs
        aligned_df = pd.concat([obs_series, perc_series, bflow_ant_series], axis=1, keys=['obs', 'perc', 'bflow_ant']).dropna()

        obs_str = aligned_df['obs'].values
        perc = aligned_df['perc'].values
        bflow_ant = aligned_df['bflow_ant'].values
        pbias = stats_df_final.loc[st, "PBIAS"]

        k_value = k_calculation(pbias, obs_str, perc, bflow_ant)

        if not np.isnan(np.log(k_value)) and (k_value < 1): # There is no recession when the Recession Constant is 1
            # If k = 1.0, the baseflow contribution will be constant, with Qt = Q0. Otherwise, to model the exponential decay typical of natural undeveloped watersheds, k must be less than 1.0.
            # If k_value is valid, update the DataFrame
            monthly_k_recessions.loc[st, "alpha_with_weights_adjusted"] = abs(np.log(k_value))
            monthly_k_recessions.loc[st, "k_recession_adjusted"] = k_value
            sts_adjusted.append(st)
        else:
            monthly_k_recessions.loc[st, "alpha_with_weights_adjusted"] = monthly_k_recessions.loc[st, "alpha_with_weights"]
            monthly_k_recessions.loc[st, "k_recession_adjusted"] = monthly_k_recessions.loc[st, "k_recession"]

    else:
        # If any required data is missing, set as the default value
        monthly_k_recessions.loc[st, "alpha_with_weights_adjusted"] = monthly_k_recessions.loc[st, "alpha_with_weights"]
        monthly_k_recessions.loc[st, "k_recession_adjusted"] = monthly_k_recessions.loc[st, "k_recession"]

print(f"Stations adjusted {len(sts_adjusted)}\n\t{sts_adjusted}")
monthly_k_recessions

Stations adjusted 2
	[4119210, 4126150]

,alpha_with_weights,k_recession,alpha_with_weights_adjusted,k_recession_adjusted
Station,,,,
3617110,0.306235,0.736213,0.306235,0.736213
3617811,0.310441,0.733124,0.310441,0.733124
3617812,0.236255,0.789579,0.236255,0.789579
3617814,0.173560,0.840667,0.173560,0.840667
3618051,0.191049,0.826092,0.191049,0.826092
...,...,...,...,...
6854601,0.908978,0.402936,0.908978,0.402936
6854713,0.559006,0.571777,0.559006,0.571777
6855411,0.729128,0.482329,0.729128,0.482329
6855412,0.572183,0.564292,0.572183,0.564292
6870640,0.967575,0.380004,0.967575,0.380004

In [13]:
monthly_k_recessions.describe().map(lambda x: f"{x:.2f}")

,alpha_with_weights,k_recession,alpha_with_weights_adjusted,k_recession_adjusted
count,808.00,808.00,808.00,808.00
mean,0.57,0.58,0.57,0.58
std,0.27,0.13,0.27,0.13
min,0.04,0.04,0.04,0.04
25%,0.40,0.50,0.41,0.50
50%,0.52,0.59,0.52,0.59
75%,0.69,0.67,0.69,0.67
max,3.24,0.96,3.24,0.96

In [19]:
# Stations that were filtered/selected previously and whose drainage areas do not contain other drainage areas
sts_filtered_not_containing = stats_df_final.index.intersection(non_containing_ws.index).tolist()

print(len(sts_filtered_not_containing))
sts_filtered_not_containing

462

[3628400,
 3630600,
 3635310,
 3637810,
 3649010,
 3649030,
 3649050,
 3649130,
 3649151,
 3649160,
 3649210,
 3649240,
 3649321,
 3649511,
 3649850,
 3649855,
 3649960,
 4103630,
 4103650,
 4113315,
 4113351,
 4113600,
 4115100,
 4115210,
 4115224,
 4115225,
 4115230,
 4115235,
 4115241,
 4115310,
 4115320,
 4115330,
 4115345,
 4115351,
 4115410,
 4116150,
 4116201,
 4116311,
 4116325,
 4116340,
 4116351,
 4116360,
 4116461,
 4118100,
 4118300,
 4118400,
 4118410,
 4118420,
 4118800,
 4119070,
 4119080,
 4119090,
 4119150,
 4119170,
 4119201,
 4119210,
 4119220,
 4119230,
 4119252,
 4119263,
 4119265,
 4119270,
 4119283,
 4119286,
 4119288,
 4119295,
 4119311,
 4119315,
 4119318,
 4119321,
 4119327,
 4119431,
 4119441,
 4119450,
 4119510,
 4120112,
 4120800,
 4120953,
 4121102,
 4121111,
 4121121,
 4121126,
 4121130,
 4121150,
 4121160,
 4121300,
 4121330,
 4121340,
 4122101,
 4122154,
 4122155,
 4122165,
 4122170,
 4122211,
 4122220,
 4122230,
 4122250,
 4122255,
 4122260,
 4122270,
 4122280,
 4123090,
 4123095,
 4123110,
 4123135,
 4123137,
 4123205,
 4123220,
 4123230,
 4123245,
 4123255,
 4123260,
 4123265,
 4123272,
 4123275,
 4123278,
 4123280,
 4123290,
 4123320,
 4123341,
 4123345,
 4123347,
 4123351,
 4123355,
 4123357,
 4123360,
 4123365,
 4123370,
 4123375,
 4123380,
 4123385,
 4123510,
 4125010,
 4125020,
 4125025,
 4125050,
 4125070,
 4125205,
 4125810,
 4125911,
 4125915,
 4125918,
 4125920,
 4125930,
 4125944,
 4126100,
 4126150,
 4126750,
 4127100,
 4127150,
 4127202,
 4127700,
 4132300,
 4132900,
 4133100,
 4133250,
 4133260,
 4133300,
 4133450,
 4133550,
 4133701,
 4135201,
 4135205,
 4135210,
 4136301,
 4143500,
 4143790,
 4146085,
 4146115,
 4146120,
 4146145,
 4146150,
 4146161,
 4146175,
 4146185,
 4146200,
 4146230,
 4146281,
 4146320,
 4146380,
 4146610,
 4146630,
 4146650,
 4146901,
 4147210,
 4147330,
 4147410,
 4147440,
 4147470,
 4147605,
 4147606,
 4147701,
 4147710,
 4147715,
 4147720,
 4147903,
 4147907,
 4147950,
 4148070,
 4148110,
 4148125,
 4148210,
 4148310,
 4148321,
 4148325,
 4148410,
 4148610,
 4148655,
 4148720,
 4148750,
 4149110,
 4149122,
 4149355,
 4149405,
 4149415,
 4149420,
 4149510,
 4149670,
 4149682,
 4149690,
 4149710,
 4149780,
 4150300,
 4150311,
 4150315,
 4150320,
 4150400,
 4150410,
 4150510,
 4150515,
 4150605,
 4150682,
 4150700,
 4150800,
 4151803,
 4152201,
 4152300,
 4152460,
 4152465,
 4152600,
 4152700,
 4152800,
 4152900,
 4203500,
 4204100,
 4207320,
 4207350,
 4208527,
 4208880,
 4213011,
 4213100,
 4213105,
 4213880,
 4214400,
 4214507,
 4215051,
 4215070,
 4215160,
 4215270,
 4215660,
 4231250,
 4231590,
 4231800,
 4232010,
 4232900,
 4234550,
 4234670,
 4235500,
 4243280,
 4243310,
 4243320,
 4244550,
 4244730,
 4244780,
 4244788,
 4244795,
 4244840,
 4244850,
 4244870,
 4244880,
 4244960,
 4244970,
 4244980,
 4244985,
 4244995,
 4247700,
 5101090,
 5101120,
 5101125,
 5101165,
 5101260,
 5101395,
 5101400,
 5101440,
 5101455,
 5101457,
 5104300,
 5104310,
 5109260,
 5202046,
 5202057,
 5202105,
 5202107,
 5202145,
 5202150,
 5202160,
 5202185,
 5202227,
 5204018,
 5204020,
 5204107,
 5204120,
 5204130,
 5204140,
 5204170,
 5204182,
 5302310,
 5304010,
 5304015,
 5304019,
 5304040,
 5304090,
 5304100,
 5405130,
 5606175,
 5607020,
 5607451,
 5608091,
 5709111,
 6118165,
 6118185,
 6119015,
 6119060,
 6119090,
 6119130,
 6119140,
 6119230,
 6119300,
 6119320,
 6121240,
 6122110,
 6122120,
 6122130,
 6122140,
 6122145,
 6122155,
 6122190,
 6122210,
 6122240,
 6123140,
 6123150,
 6123171,
 6123181,
 6123190,
 6123200,
 6123210,
 6123220,
 6123230,
 6123250,
 6123270,
 6123350,
 6123380,
 6123410,
 6123420,
 6123430,
 6123440,
 6123461,
 6123470,
 6123645,
 6123700,
 6123720,
 6123730,
 6123750,
 6123770,
 6123780,
 6123790,
 6123800,
 6123810,
 6123825,
 6124200,
 6124420,
 6124510,
 6124520,
 6124600,
 6125260,
 6125362,
 6125440,
 6125600,
 6125610,
 6125650,
 6125660,
 6125670,
 6125710,
 6128200,
 6128220,
 6128630,
 6128701,
 6128720,
 6135110,
 6135210,
 6136100,
 6136151,
 6136160,
 6136202,
 6136520,
 6139060,
 6139140,
 6139201,
 6139220,
 6139240,
 6139261,
 6139310,
 6139502,
 6139520,
 6139530,
 6139680,
 6139770,
 6139825,
 6139832,
 6139910,
 6139935,
 6139940,
 6139960,
 6142660,
 6144350,
 6172050,
 6172055,
 6172220,
 6172260,
 6233150,
 6233350,
 6401111,
 6456105,
 6457240,
 6457730,
 6457880,
 6457985,
 6457990,
 6458615,
 6458753,
 6603100,
 6604100,
 6604310,
 6605815,
 6606200,
 6606347,
 6606510,
 6607140,
 6607550,
 6607950,
 6608200,
 6608500,
 6742451,
 6742701,
 6744200,
 6744500,
 6830101,
 6854601,
 6854713,
 6855411,
 6855412,
 6870640]